version: '3.8'

services:
  quiz-app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      - ./data:/app/server/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:4000/api/judges?user=healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
